package com.fhy.pojo;

public class Gcar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gcar.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gcar.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gcar.gtime
     *
     * @mbggenerated
     */
    private String gtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gcar.gstatus
     *
     * @mbggenerated
     */
    private Integer gstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gcar.id
     *
     * @return the value of gcar.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gcar.id
     *
     * @param id the value for gcar.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gcar.user_id
     *
     * @return the value of gcar.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gcar.user_id
     *
     * @param userId the value for gcar.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gcar.gtime
     *
     * @return the value of gcar.gtime
     *
     * @mbggenerated
     */
    public String getGtime() {
        return gtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gcar.gtime
     *
     * @param gtime the value for gcar.gtime
     *
     * @mbggenerated
     */
    public void setGtime(String gtime) {
        this.gtime = gtime == null ? null : gtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gcar.gstatus
     *
     * @return the value of gcar.gstatus
     *
     * @mbggenerated
     */
    public Integer getGstatus() {
        return gstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gcar.gstatus
     *
     * @param gstatus the value for gcar.gstatus
     *
     * @mbggenerated
     */
    public void setGstatus(Integer gstatus) {
        this.gstatus = gstatus;
    }
}